[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
termcolor = { version = "1.1" }
home = { version = "0.5.0" }
serde = { version = "1.0.0", features = ["derive"] }
serde_json = { version = "1.0.68" }
